/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseNode: typeof import('./src/components/workflow/nodes/BaseNode.vue')['default']
    DeviceMonitor: typeof import('./src/components/workflow/DeviceMonitor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExecutionProgress: typeof import('./src/components/workflow/ExecutionProgress.vue')['default']
    FlowCanvas: typeof import('./src/components/workflow/FlowCanvas.vue')['default']
    MonitorPanel: typeof import('./src/components/workflow/MonitorPanel.vue')['default']
    NodeParams: typeof import('./src/components/workflow/NodeParams.vue')['default']
    NodeSearch: typeof import('./src/components/workflow/NodeSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutsHelp: typeof import('./src/components/workflow/ShortcutsHelp.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Toolbar: typeof import('./src/components/workflow/Toolbar.vue')['default']
    TrainingMetrics: typeof import('./src/components/workflow/TrainingMetrics.vue')['default']
    WorkflowCanvas: typeof import('./src/components/workflow/WorkflowCanvas.vue')['default']
    WorkflowLayout: typeof import('./src/components/workflow/WorkflowLayout.vue')['default']
  }
}
